import { Screen, BibleBook } from './types';

export const NAV_ITEMS = [
    { id: Screen.Home, label: 'Home', icon: 'home' },
    { id: Screen.Bible, label: 'Bible', icon: 'menu_book' },
    { id: Screen.Notes, label: 'Notes', icon: 'edit_note' },
    { id: Screen.Library, label: 'Library', icon: 'bookmark' },
    { id: Screen.Search, label: 'Search', icon: 'search' },
];

export const BIBLE_BOOKS: BibleBook[] = [
  // Old Testament
  { name: 'Genesis', abbr: 'Gen', chapters: 50, testament: 'OT' },
  { name: 'Exodus', abbr: 'Exo', chapters: 40, testament: 'OT' },
  { name: 'Leviticus', abbr: 'Lev', chapters: 27, testament: 'OT' },
  { name: 'Numbers', abbr: 'Num', chapters: 36, testament: 'OT' },
  { name: 'Deuteronomy', abbr: 'Deu', chapters: 34, testament: 'OT' },
  { name: 'Joshua', abbr: 'Jos', chapters: 24, testament: 'OT' },
  { name: 'Judges', abbr: 'Jdg', chapters: 21, testament: 'OT' },
  { name: 'Ruth', abbr: 'Rth', chapters: 4, testament: 'OT' },
  { name: '1 Samuel', abbr: '1Sa', chapters: 31, testament: 'OT' },
  { name: '2 Samuel', abbr: '2Sa', chapters: 24, testament: 'OT' },
  { name: '1 Kings', abbr: '1Ki', chapters: 22, testament: 'OT' },
  { name: '2 Kings', abbr: '2Ki', chapters: 25, testament: 'OT' },
  { name: '1 Chronicles', abbr: '1Ch', chapters: 29, testament: 'OT' },
  { name: '2 Chronicles', abbr: '2Ch', chapters: 36, testament: 'OT' },
  { name: 'Ezra', abbr: 'Ezr', chapters: 10, testament: 'OT' },
  { name: 'Nehemiah', abbr: 'Neh', chapters: 13, testament: 'OT' },
  { name: 'Esther', abbr: 'Est', chapters: 10, testament: 'OT' },
  { name: 'Job', abbr: 'Job', chapters: 42, testament: 'OT' },
  { name: 'Psalms', abbr: 'Psa', chapters: 150, testament: 'OT' },
  { name: 'Proverbs', abbr: 'Pro', chapters: 31, testament: 'OT' },
  { name: 'Ecclesiastes', abbr: 'Ecc', chapters: 12, testament: 'OT' },
  { name: 'Song of Solomon', abbr: 'Sng', chapters: 8, testament: 'OT' },
  { name: 'Isaiah', abbr: 'Isa', chapters: 66, testament: 'OT' },
  { name: 'Jeremiah', abbr: 'Jer', chapters: 52, testament: 'OT' },
  { name: 'Lamentations', abbr: 'Lam', chapters: 5, testament: 'OT' },
  { name: 'Ezekiel', abbr: 'Eze', chapters: 48, testament: 'OT' },
  { name: 'Daniel', abbr: 'Dan', chapters: 12, testament: 'OT' },
  { name: 'Hosea', abbr: 'Hos', chapters: 14, testament: 'OT' },
  { name: 'Joel', abbr: 'Joe', chapters: 3, testament: 'OT' },
  { name: 'Amos', abbr: 'Amo', chapters: 9, testament: 'OT' },
  { name: 'Obadiah', abbr: 'Oba', chapters: 1, testament: 'OT' },
  { name: 'Jonah', abbr: 'Jon', chapters: 4, testament: 'OT' },
  { name: 'Micah', abbr: 'Mic', chapters: 7, testament: 'OT' },
  { name: 'Nahum', abbr: 'Nah', chapters: 3, testament: 'OT' },
  { name: 'Habakkuk', abbr: 'Hab', chapters: 3, testament: 'OT' },
  { name: 'Zephaniah', abbr: 'Zep', chapters: 3, testament: 'OT' },
  { name: 'Haggai', abbr: 'Hag', chapters: 2, testament: 'OT' },
  { name: 'Zechariah', abbr: 'Zec', chapters: 14, testament: 'OT' },
  { name: 'Malachi', abbr: 'Mal', chapters: 4, testament: 'OT' },
  // New Testament
  { name: 'Matthew', abbr: 'Mat', chapters: 28, testament: 'NT' },
  { name: 'Mark', abbr: 'Mar', chapters: 16, testament: 'NT' },
  { name: 'Luke', abbr: 'Luk', chapters: 24, testament: 'NT' },
  { name: 'John', abbr: 'Jhn', chapters: 21, testament: 'NT' },
  { name: 'Acts', abbr: 'Act', chapters: 28, testament: 'NT' },
  { name: 'Romans', abbr: 'Rom', chapters: 16, testament: 'NT' },
  { name: '1 Corinthians', abbr: '1Co', chapters: 16, testament: 'NT' },
  { name: '2 Corinthians', abbr: '2Co', chapters: 13, testament: 'NT' },
  { name: 'Galatians', abbr: 'Gal', chapters: 6, testament: 'NT' },
  { name: 'Ephesians', abbr: 'Eph', chapters: 6, testament: 'NT' },
  { name: 'Philippians', abbr: 'Php', chapters: 4, testament: 'NT' },
  { name: 'Colossians', abbr: 'Col', chapters: 4, testament: 'NT' },
  { name: '1 Thessalonians', abbr: '1Th', chapters: 5, testament: 'NT' },
  { name: '2 Thessalonians', abbr: '2Th', chapters: 3, testament: 'NT' },
  { name: '1 Timothy', abbr: '1Ti', chapters: 6, testament: 'NT' },
  { name: '2 Timothy', abbr: '2Ti', chapters: 4, testament: 'NT' },
  { name: 'Titus', abbr: 'Tit', chapters: 3, testament: 'NT' },
  { name: 'Philemon', abbr: 'Phm', chapters: 1, testament: 'NT' },
  { name: 'Hebrews', abbr: 'Heb', chapters: 13, testament: 'NT' },
  { name: 'James', abbr: 'Jam', chapters: 5, testament: 'NT' },
  { name: '1 Peter', abbr: '1Pe', chapters: 5, testament: 'NT' },
  { name: '2 Peter', abbr: '2Pe', chapters: 3, testament: 'NT' },
  { name: '1 John', abbr: '1Jn', chapters: 5, testament: 'NT' },
  { name: '2 John', abbr: '2Jn', chapters: 1, testament: 'NT' },
  { name: '3 John', abbr: '3Jn', chapters: 1, testament: 'NT' },
  { name: 'Jude', abbr: 'Jud', chapters: 1, testament: 'NT' },
  { name: 'Revelation', abbr: 'Rev', chapters: 22, testament: 'NT' },
];

export const AVAILABLE_TRANSLATIONS = [
    { id: 'kjv', name: 'KJV', description: 'King James Version' },
    { id: 'web', name: 'WEB', description: 'World English Bible' },
];

export const AVAILABLE_RESOURCES = [
    { id: 'spurgeon-sermons', name: 'Spurgeon\'s Sermon Notes', description: 'Complete collection of 214 sermon notes.' }
];